# TCL File Generated by Component Editor 13.1
# Wed Dec 03 11:48:33 CET 2014
# DO NOT MODIFY


# 
# oc_i2c_master "oc_i2c_master" v8.0
# RF 2014.12.03.11:48:33
# opencores.org I2C Master controller
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module oc_i2c_master
# 
set_module_property DESCRIPTION "opencores.org I2C Master controller"
set_module_property NAME oc_i2c_master
set_module_property VERSION 8.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "DE1 Components"
set_module_property AUTHOR RF
set_module_property DISPLAY_NAME oc_i2c_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL oc_i2c_master
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file oc_i2c_master.v VERILOG PATH oc_i2c_master.v TOP_LEVEL_FILE
add_fileset_file i2c_master_bit_ctrl.v VERILOG PATH i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG PATH i2c_master_byte_ctrl.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file oc_i2c_master.v VERILOG PATH oc_i2c_master.v
add_fileset_file i2c_master_bit_ctrl.v VERILOG PATH i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG PATH i2c_master_byte_ctrl.v


# 
# parameters
# 
add_parameter CLK_FREQ INTEGER 25000000 ""
set_parameter_property CLK_FREQ DEFAULT_VALUE 25000000
set_parameter_property CLK_FREQ DISPLAY_NAME CLK_FREQ
set_parameter_property CLK_FREQ WIDTH ""
set_parameter_property CLK_FREQ TYPE INTEGER
set_parameter_property CLK_FREQ UNITS None
set_parameter_property CLK_FREQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQ DESCRIPTION ""
set_parameter_property CLK_FREQ AFFECTS_GENERATION false
set_parameter_property CLK_FREQ SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property CLK_FREQ SYSTEM_INFO_ARG mm_clk


# 
# display items
# 


# 
# connection point mm_clk
# 
add_interface mm_clk clock end
set_interface_property mm_clk clockRate 0
set_interface_property mm_clk ENABLED true
set_interface_property mm_clk EXPORT_OF ""
set_interface_property mm_clk PORT_NAME_MAP ""
set_interface_property mm_clk CMSIS_SVD_VARIABLES ""
set_interface_property mm_clk SVD_ADDRESS_GROUP ""

add_interface_port mm_clk wb_clk_i clk Input 1


# 
# connection point mm_clk_reset
# 
add_interface mm_clk_reset reset end
set_interface_property mm_clk_reset associatedClock mm_clk
set_interface_property mm_clk_reset synchronousEdges DEASSERT
set_interface_property mm_clk_reset ENABLED true
set_interface_property mm_clk_reset EXPORT_OF ""
set_interface_property mm_clk_reset PORT_NAME_MAP ""
set_interface_property mm_clk_reset CMSIS_SVD_VARIABLES ""
set_interface_property mm_clk_reset SVD_ADDRESS_GROUP ""

add_interface_port mm_clk_reset wb_rst_i reset Input 1


# 
# connection point mm_slave
# 
add_interface mm_slave avalon end
set_interface_property mm_slave addressAlignment NATIVE
set_interface_property mm_slave addressUnits WORDS
set_interface_property mm_slave associatedClock mm_clk
set_interface_property mm_slave associatedReset mm_clk_reset
set_interface_property mm_slave bitsPerSymbol 8
set_interface_property mm_slave burstOnBurstBoundariesOnly false
set_interface_property mm_slave burstcountUnits WORDS
set_interface_property mm_slave explicitAddressSpan 0
set_interface_property mm_slave holdTime 0
set_interface_property mm_slave linewrapBursts false
set_interface_property mm_slave maximumPendingReadTransactions 0
set_interface_property mm_slave readLatency 0
set_interface_property mm_slave readWaitStates 0
set_interface_property mm_slave readWaitTime 0
set_interface_property mm_slave setupTime 0
set_interface_property mm_slave timingUnits Cycles
set_interface_property mm_slave writeWaitTime 0
set_interface_property mm_slave ENABLED true
set_interface_property mm_slave EXPORT_OF ""
set_interface_property mm_slave PORT_NAME_MAP ""
set_interface_property mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property mm_slave SVD_ADDRESS_GROUP ""

add_interface_port mm_slave wb_dat_i writedata Input 8
add_interface_port mm_slave wb_dat_o readdata Output 8
add_interface_port mm_slave wb_we_i write Input 1
add_interface_port mm_slave wb_cyc_i chipselect Input 1
add_interface_port mm_slave wb_ack_o waitrequest_n Output 1
add_interface_port mm_slave wb_adr_i address Input 3
set_interface_assignment mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point i2c_exports
# 
add_interface i2c_exports conduit end
set_interface_property i2c_exports associatedClock mm_clk
set_interface_property i2c_exports associatedReset mm_clk_reset
set_interface_property i2c_exports ENABLED true
set_interface_property i2c_exports EXPORT_OF ""
set_interface_property i2c_exports PORT_NAME_MAP ""
set_interface_property i2c_exports CMSIS_SVD_VARIABLES ""
set_interface_property i2c_exports SVD_ADDRESS_GROUP ""

add_interface_port i2c_exports scl export Bidir 1
add_interface_port i2c_exports sda export Bidir 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint mm_slave
set_interface_property interrupt_sender associatedClock mm_clk
set_interface_property interrupt_sender associatedReset mm_clk_reset
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender wb_inta_o irq Output 1

