# TCL File Generated by Component Editor 9.1
# Fri Jun 25 10:41:47 CEST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | CPU_FiFo_Bridge "CPU_FiFo_Bridge" v1.0
# | Stephan Schuler 2010.06.25.10:41:47
# | Bidirektionale Kommunikation über Fifos
# | 
# | C:/USERS/Stephan/SoPC1/CPU_FiFo_Bridge.vhd
# | 
# |    ./CPU_FiFo_Bridge.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module CPU_FiFo_Bridge
# | 
set_module_property DESCRIPTION "Bidirektionale Kommunikation über Fifos"
set_module_property NAME CPU_FiFo_Bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Bridge
set_module_property AUTHOR "Stephan Schuler"
set_module_property DISPLAY_NAME CPU_FiFo_Bridge
set_module_property TOP_LEVEL_HDL_FILE CPU_FiFo_Bridge.vhd
set_module_property TOP_LEVEL_HDL_MODULE CPU_FiFo_Bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file CPU_FiFo_Bridge.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
add_interface_port clock reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s0
# | 
add_interface s0 avalon end
set_interface_property s0 addressAlignment DYNAMIC
set_interface_property s0 associatedClock clock
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 isMemoryDevice false
set_interface_property s0 isNonVolatileStorage false
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 printableDevice false
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitStates 0
set_interface_property s0 readWaitTime 0
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0

set_interface_property s0 ASSOCIATED_CLOCK clock
set_interface_property s0 ENABLED true

add_interface_port s0 cpu1_address address Input 8
add_interface_port s0 cpu1_read read Input 1
add_interface_port s0 cpu1_readdata readdata Output 32
add_interface_port s0 cpu1_write write Input 1
add_interface_port s0 cpu1_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq0
# | 
add_interface irq0 interrupt end
set_interface_property irq0 associatedAddressablePoint s0

set_interface_property irq0 ASSOCIATED_CLOCK clock
set_interface_property irq0 ENABLED true

add_interface_port irq0 cpu1_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 associatedClock clock
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 0
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK clock
set_interface_property s1 ENABLED true

add_interface_port s1 cpu2_address address Input 8
add_interface_port s1 cpu2_read read Input 1
add_interface_port s1 cpu2_readdata readdata Output 32
add_interface_port s1 cpu2_writedata writedata Input 32
add_interface_port s1 cpu2_write write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq1
# | 
add_interface irq1 interrupt end
set_interface_property irq1 associatedAddressablePoint s1

set_interface_property irq1 ASSOCIATED_CLOCK clock
set_interface_property irq1 ENABLED true

add_interface_port irq1 cpu2_irq irq Output 1
# | 
# +-----------------------------------
